# Generated by Django 3.2.5 on 2022-03-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidPer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_per', models.CharField(max_length=50)),
            ],
        ),
    ]
